package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 11, 2018 8:09:41 AM NPT
*/

public interface HelloOperations 
{
  String sayHello ();
  int sum (int a, int b);
  void shutdown ();
} // interface HelloOperations
